import type { ProductBlueprint } from "../types/ai.js";
import type { ScaffoldFile } from "../templates/scaffold.js";
import {
  PREINSTALLED_PACKAGES,
  SCAFFOLD_PATHS,
} from "../templates/scaffold.js";

export type CodeGenMode = "create" | "edit";

const SCAFFOLD_LIST = SCAFFOLD_PATHS.map((path) => `   - ${path}`).join("\n");

const CREATE_RULES = `NON-NEGOTIABLE OUTPUT RULES:
1. Emit ONLY <forgeAction> blocks. Never emit a <forgeArtifact> wrapper, and never write any prose, headings, or summary text.
2. The following files ALREADY EXIST. Never emit them:
${SCAFFOLD_LIST}
3. Never emit <forgeAction type="shell"> for scaffolding. Do NOT emit "npm create", "npm install -D", "npx ... init", "cd", or any command that generates a project. Every package you need is installed already.
4. Every file path MUST live under src/. Never write to the project root.
5. src/App.tsx MUST exist and MUST default-export the root React component.
6. Import ONLY from the packages listed below. If you need behaviour that is not on that list, implement it yourself in the project. Never import an unlisted package such as axios, lodash, uuid, nanoid, or framer-motion. For unique ids call crypto.randomUUID() — it is built into the browser and needs no import.
7. Output raw source code. Never escape characters for markup or encoding. In JavaScript template literals, write backticks and placeholder syntax literally, exactly as they appear in normal, valid source code.`;

const EDIT_RULES = `NON-NEGOTIABLE OUTPUT RULES:
1. You are MODIFYING an application that already exists and already runs. You are not rewriting it.
2. Emit ONLY the files that must change to satisfy the request. Never re-emit a file you did not change — unchanged files are preserved automatically, and re-emitting them wastes your entire output budget.
3. For every file you do change, emit its COMPLETE new content. Never emit a diff, a fragment, an elided region, or a comment such as "// rest unchanged". A partial file will corrupt the application.
4. The following files are generated by Forge. Never emit them, even if the change seems to require it:
${SCAFFOLD_LIST}
5. Never emit <forgeAction type="shell"> and never add, remove, or upgrade a dependency. Every package you need is already installed.
6. Every file path MUST live under src/. src/App.tsx must keep default-exporting the root React component — never rename or relocate it.
7. Preserve the existing architecture, file layout, naming, imports, and Tailwind styling conventions. The change must read as if the original author wrote it.
8. Keep every feature that already works working. This is a targeted change, not an opportunity to refactor.
9. Import ONLY from the packages listed below. Never import an unlisted package such as axios, lodash, uuid, nanoid, or framer-motion. For unique ids call crypto.randomUUID().
10. Output raw source code. Never escape characters for markup or encoding. In JavaScript template literals, write backticks and placeholder syntax literally, exactly as they appear in normal, valid source code.`;

const STACK = `STACK YOU ARE WRITING FOR:
- React 19 with TypeScript, bundled by Vite.
- Tailwind CSS v4. Use standard utility classes directly on elements.
- The theme defines primary-400/500/600/700 and accent-400/500/600. Use them as bg-primary-500, text-accent-400, border-primary-600 and so on.
- Dark UI is the default and expected look: bg-zinc-950 canvas, bg-zinc-900/60 cards, border-zinc-800 borders, text-zinc-50 headings, text-zinc-400 body copy.
- src/main.tsx already wraps your App in a HashRouter, so react-router-dom's Routes, Route and Link work. Always use HashRouter-compatible navigation. NEVER use BrowserRouter.
- Routing is optional. Prefer a useState-driven view switch for simple apps; only reach for routes when the app genuinely has distinct pages.
- lucide-react is the only icon library. recharts and date-fns are available for charts and dates.`;

const ANTI_SLOP = `ANTI-SLOP REQUIREMENTS:
1. NO PLACEHOLDER COMMENTS. Never write "// TODO", "// Add more items here", "// Implement later", or any stub. Every function must be fully implemented.
2. NO EMPTY OR SKELETON COMPONENTS. If you declare a component, it renders real, finished markup.
3. Use realistic mock data with believable names, amounts, dates and statuses. Never "Item 1", "Lorem ipsum", or "foo/bar".
4. Build real interactive state: working search filters, tab switching, modals that open and close, form validation, sortable tables, optimistic updates.
5. Visual quality bar: consistent spacing rhythm, subtle borders (border-zinc-800), clear hover states (hover:bg-zinc-800/50 transition-colors), rounded-lg or rounded-xl surfaces, readable type hierarchy. No default unstyled HTML controls.
6. Organise the code: types in src/types.ts, mock data in src/mockData.ts, presentational components in src/components/, page-level views in src/pages/.`;

const CREATE_EXAMPLE = `EXACT OUTPUT SHAPE — repeat this pattern, nothing before or after it:
<forgeAction type="file" filePath="src/types.ts">
export interface Invoice {
  id: string;
  client: string;
  amount: number;
  status: "paid" | "pending" | "overdue";
}
</forgeAction>
<forgeAction type="file" filePath="src/App.tsx">
import { useState } from "react";

export default function App() {
  const [active, setActive] = useState("overview");
  return <main className="min-h-screen bg-zinc-950 text-zinc-50">{active}</main>;
}
</forgeAction>

Begin now with your first <forgeAction> block.`;

const EDIT_EXAMPLE = `EXACT OUTPUT SHAPE — repeat this pattern, nothing before or after it:
<forgeAction type="file" filePath="src/components/Header.tsx">
import { Menu } from "lucide-react";

export function Header({ onMenu }: { onMenu: () => void }) {
  return (
    <header className="sticky top-0 z-20 border-b border-zinc-800 bg-zinc-950/80 backdrop-blur">
      <button type="button" onClick={onMenu} className="p-2 transition-colors hover:bg-zinc-800/50">
        <Menu className="size-4" />
      </button>
    </header>
  );
}
</forgeAction>

If exactly one file changes, emit exactly one block. Begin now with your first <forgeAction> block.`;

function designTokens(blueprint?: ProductBlueprint): string {
  if (!blueprint?.designSystem) {
    return `  - Primary Accent: Indigo
  - Neutral Baseline: Zinc
  - Layout Architecture: Sidebar navigation with a dashboard grid`;
  }

  const { designSystem } = blueprint;
  return `  - Primary Accent: ${designSystem.primaryColor}
  - Neutral Baseline: ${designSystem.neutralBase}
  - Layout Architecture: ${designSystem.layoutPattern}
  - Heading Font: ${designSystem.typography.headingFont}, Body: ${designSystem.typography.bodyFont}`;
}

export function buildCodeGenSystemPrompt(
  blueprint?: ProductBlueprint,
  mode: CodeGenMode = "create",
): string {
  const rules = mode === "edit" ? EDIT_RULES : CREATE_RULES;
  const example = mode === "edit" ? EDIT_EXAMPLE : CREATE_EXAMPLE;

  return `You are Forge Studio's Principal Software Engineer.
You write production-grade, complete, beautiful React applications.

The project is ALREADY scaffolded and its dependencies are ALREADY installed. You only write application source files.

${rules}

AVAILABLE PACKAGES (already installed, import them directly):
${PREINSTALLED_PACKAGES.join(", ")}

${STACK}

${ANTI_SLOP}

DESIGN BLUEPRINT:
${designTokens(blueprint)}

${example}`;
}

export function buildCodeGenUserPrompt(
  prompt: string,
  blueprint?: ProductBlueprint,
): string {
  if (!blueprint) {
    return `Build the complete application described here:

${prompt}

Write every file the app needs under src/. Remember: no scaffolding commands, no root-level files, no placeholder code.`;
  }

  return `Build the complete application "${blueprint.title}".

OVERVIEW
${blueprint.description}

TARGET AUDIENCE
${blueprint.targetAudience}

FEATURES TO IMPLEMENT
${blueprint.features.map((feature) => `- ${feature}`).join("\n")}

DATA MODEL
${blueprint.entityModels
  .map((entity) => `- ${entity.name}: ${entity.fields.join(", ")}`)
  .join("\n")}

ORIGINAL USER REQUEST
${prompt}

Write every file the app needs under src/. Remember: no scaffolding commands, no root-level files, no placeholder code.`;
}

export function buildEditUserPrompt(
  instruction: string,
  files: ScaffoldFile[],
): string {
  const codebase = files
    .map((file) => `<currentFile path="${file.path}">\n${file.content}\n</currentFile>`)
    .join("\n\n");

  return `CHANGE REQUEST
${instruction}

CURRENT PROJECT FILES — ${files.length} files, complete and up to date
${codebase}

Apply the change request to this codebase. Emit only the files you modify, each one in full.`;
}
